### ISSUE TITLE
Broken link checker should catch links that respond with a 404

### ISSUE THREAD

**Issue by agentolivia** [OsioLabs/osiolabs-copyeditor#17]
QA: If links return a 404, they should be marked as broken in `lint` or `review` npm scripts and a FAILURE or ERROR should be returned.

On /tutorials/theming/underscorejs-theme-or-module.md, there are 2 broken links. But when I run

`npm run lint tutorials/theming/underscorejs-theme-or-module.md`

This returns "no issues found"

And when I run

`npm run review tutorials/theming/underscorejs-theme-or-module.md`

I get grammar warnings but no failures/errors due to broken links.

**Comment by eojthebrave** [comment]
In my testing so far, it looks like there is some kind of conflict between the `preset-lint-markdown-style-guide` and `remark-lint-no-dead-urls` plugins we're using. If I disable the markdown style guide one the linter finds the broken URLs. But if I turn it on again it doesn't. :/

I guess I'll start by upgrading all the packages to their latest versions and seeing what happens.

**Comment by eojthebrave** [comment]
Further testing indicates that this issue is caused by adding the `<!--lint disable-->` comments. Which seems to have some weird effects with sort of surpresses the output of errors. If you remove that from the file it'll output info about the broken links.

I believe what happens is when you do `<!-- lint disable -->` it disables it for the whole file. However, since these things run asynchronosly, anything that executes before it gets to the `disable` gets to report it's errors. And anything that logs an error after the `disable` is ignored.

I think maybe the best path forward here will be to write our own plugin that runs before all the linting rules and just deletes everything after the `<!-- internal -->` tag. And then stop using the `<!-- lint disable -->` all together.

The alternative would be to always add an `<!--lint enable-->` at the end of every file.

**Comment by eojthebrave** [comment]
This is resolved now. The above comment is accurate. And we need to just stop using the `<!--lint disable-->` comment like we have been as it's not intended to be used that way.

Instead, I added a step that will drop everything in the document after the `<!-- internal -->` tag, as well as remove any existing `<!--lint disable-->` before is starts running the linter.
